name: timerf1c
description: A f1c timer controller.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  liquid_progress_indicator: ^0.4.0
  path_provider: ^2.0.2
  usb_serial: ^0.3.0
  shared_preferences: ^2.0.0
  intl: ^0.17.0
  expandable_bottom_sheet: ^1.1.0
  flutter_animator: ^3.1.2
  flutter_blue: ^0.8.0
  flutter_map_location_marker: "any"
  flutter_map: ^0.13.1
  provider: ^5.0.0
  tuple: ^2.0.0
  auto_size_text: "3.0.0-nullsafety.0"
  lottie: ^1.1.0
  flushbar: ^1.10.2
  responsive_grid: ^2.0.0
  awesome_dialog: ^2.1.0
  location: ^4.3.0
  flutter_svg: ^0.22.0
  cool_stepper: ^1.1.1
  page_transition: ^2.0.2
  flutter:
    sdk: flutter
  sqflite:
  flutter_file_dialog: ^2.1.0
  csv: ^5.0.0
  share_extend: "^2.0.0"
  flutter_paginator: "0.0.6"
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_map_tile_caching: ^3.0.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/bluetooth-connected.json
    - assets/animations/bluetooth-connecting.json
    - assets/animations/error-animation.json
    - assets/animations/bluetooth-off.json
    - assets/animations/start-scanning.json
    - assets/res/bluetooth_receiver_data.txt
    - assets/images/logo.svg
    - assets/images/device-not-found.png
    - assets/icons/plain_marker.svg
    - assets/icons/plain_start.svg
    - assets/icons/plain_end.svg
    - assets/animations/turn-on-timerf1c.json
    - assets/animations/loading.json
    - assets/animations/download-success.json
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
