name: timer_f1
version: 1.1.0
publish_to: none
description: Timer F1C app
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  objectbox: ^1.4.1-dev.0
  objectbox_flutter_libs: 1.4.1-dev.0
  location: ^4.3.0
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.3
  rxdart: ^0.27.3
  flutter_hooks: ^0.18.2+1
  get_storage: ^2.0.3
  flutter_reactive_ble: ^5.0.2
  usb_serial: ^0.4.0
  go_router: ^3.0.1
  latlong2: ^0.8.1
  another_flushbar: ^1.10.28
  lottie: ^1.2.1
  flutter_animator: ^3.2.0
  flutter_svg: ^1.0.0
  auto_size_text: '3.0.0'
  awesome_dialog: ^2.1.2
  permission_handler: ^8.3.0
  expandable_bottom_sheet: ^1.1.1+1
  responsive_grid: ^2.0.0
  flutter_map: ^0.14.0
  flutter_map_location_marker: ^3.0.2
  geolocator: ^8.2.0
  csv: ^5.0.1
  share_extend: '^2.0.0'
  flutter_file_dialog: ^2.3.0
  flutter_settings_ui: ^2.0.1
  package_info_plus: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.0
  objectbox_generator: 1.4.1-dev.0
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/settings.png
    - assets/animations/bluetooth-connected.json
    - assets/animations/bluetooth-connecting.json
    - assets/animations/error-animation.json
    - assets/animations/bluetooth-off.json
    - assets/animations/start-scanning.json
    - assets/images/logo.svg
    - assets/images/device-not-found.png
    - assets/icons/plain_marker.svg
    - assets/icons/plain_start.svg
    - assets/icons/plain_end.svg
    - assets/animations/turn-on-timerf1c.json
    - assets/animations/loading.json
    - assets/animations/download-success.json
    - assets/animations/invalid-timer-brand.json
    - assets/animations/device-disconnected.json
