name: timer_f1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  location: ^4.3.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_reactive_ble: ^5.0.2
  usb_serial: ^0.4.0
  latlong2: ^0.8.1
  another_flushbar: ^1.10.28
  lottie: ^1.2.1
  flutter_animator: ^3.2.0
  flutter_svg: ^1.0.0
  auto_size_text: "3.0.0"
  awesome_dialog: ^2.1.2
  permission_handler: ^8.3.0

dev_dependencies: 
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/animations/bluetooth-connected.json
    - assets/animations/bluetooth-connecting.json
    - assets/animations/error-animation.json
    - assets/animations/bluetooth-off.json
    - assets/animations/start-scanning.json
    - assets/images/logo.svg
    - assets/images/device-not-found.png
    - assets/icons/plain_marker.svg
    - assets/icons/plain_start.svg
    - assets/icons/plain_end.svg
    - assets/animations/turn-on-timerf1c.json
    - assets/animations/loading.json
    - assets/animations/download-success.json
