name: timer_f1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  location: ^4.3.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter: 
    sdk: flutter
  latlong2: ^0.8.1
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  flutter_reactive_ble: ^5.0.2
  usb_serial: ^0.4.0

dev_dependencies: 
  build_runner: ^2.0.0
  objectbox_generator: any
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

