// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/data/models/flight_data_model.dart';
import 'app/data/models/flight_model.dart';
import 'app/data/models/program.dart';
import 'app/data/models/servo.dart';
import 'app/data/models/timer_configuration.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3617741553367741416),
      name: 'Flight',
      lastPropertyId: const IdUid(17, 852303600115363581),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8197531307069830182),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3119362607594110509),
            name: 'startTimestamp',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7065487454957984963),
            name: 'durationInMs',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7000256746130150781),
            name: 'endTimestamp',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 3820573597573610140),
            name: 'planeId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 5286937463019224857),
            name: 'maxPressure',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5281464452431523957),
            name: 'maxHeight',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 6349820843352883293),
            name: 'maxTemperature',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 1707142063431928861),
            name: 'farPlaneDistanceLat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2557690390243076247),
            name: 'farPlaneDistanceLng',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 260385017123311303),
            name: 'startFlightLng',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 3021449412803215971),
            name: 'startFlightLat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 4986105825531599917),
            name: 'endFlightLng',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 8577958606838120936),
            name: 'endFlightLat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 3708300250080366842),
            name: 'maxPlaneDistanceFromStart',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 757837763565641298),
            name: 'maxPlaneDistanceFromUser',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 852303600115363581),
            name: 'flightAddress',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'flightData', srcEntity: 'FlightData', srcField: 'flight')
      ]),
  ModelEntity(
      id: const IdUid(2, 1996917656354719130),
      name: 'FlightData',
      lastPropertyId: const IdUid(15, 3085372596932118392),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5761424148726819047),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 955355203143129608),
            name: 'isConnectedToPlane',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3034893611289659868),
            name: 'flightHistoryId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3796642959493733523),
            name: 'planeId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7728617168268401784),
            name: 'timestamp',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4043674209865252467),
            name: 'planeLat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 5130337363462404811),
            name: 'planeLng',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 675320341134320462),
            name: 'height',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 6048122397642438921),
            name: 'temperature',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 697926613373307829),
            name: 'pressure',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 3924585362923200929),
            name: 'voltage',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 5447326414969738812),
            name: 'userLng',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 5622336359712150334),
            name: 'userLat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 5009816197382593742),
            name: 'isInitial',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 3085372596932118392),
            name: 'flightId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 5182127689446183035),
            relationTarget: 'Flight')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 2193015486373281114),
      name: 'Program',
      lastPropertyId: const IdUid(4, 4066208250836667911),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5561007999418306729),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5774301234943724802),
            name: 'time',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 8670529558916408178),
            name: 'rotation',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4066208250836667911),
            name: 'servoId',
            type: 11,
            flags: 520,
            indexId: const IdUid(2, 3854474950964882710),
            relationTarget: 'Servo')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(5, 553770475019406838),
      name: 'Servo',
      lastPropertyId: const IdUid(3, 2366463627940278094),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3736744247678785430),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 385968381398050751),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 2366463627940278094),
            name: 'timerConfigurationId',
            type: 11,
            flags: 520,
            indexId: const IdUid(3, 2073944158793052802),
            relationTarget: 'TimerConfiguration')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'program', srcEntity: 'Program', srcField: 'servo')
      ]),
  ModelEntity(
      id: const IdUid(7, 7894768153648976925),
      name: 'TimerConfiguration',
      lastPropertyId: const IdUid(3, 1409326336159371176),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1553974021383400304),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3543977496437803216),
            name: 'ledOn',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1409326336159371176),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(
            name: 'servos', srcEntity: 'Servo', srcField: 'timerConfiguration')
      ])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(7, 7894768153648976925),
      lastIndexId: const IdUid(3, 2073944158793052802),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [4466057026167610518, 6145684746531592935],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        5819823023752054217,
        7477028276912578726,
        8235972078413561412,
        5104838492584877097
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Flight: EntityDefinition<Flight>(
        model: _entities[0],
        toOneRelations: (Flight object) => [],
        toManyRelations: (Flight object) => {
              RelInfo<FlightData>.toOneBacklink(15, object.id,
                  (FlightData srcObject) => srcObject.flight): object.flightData
            },
        getId: (Flight object) => object.id,
        setId: (Flight object, int id) {
          object.id = id;
        },
        objectToFB: (Flight object, fb.Builder fbb) {
          final planeIdOffset =
              object.planeId == null ? null : fbb.writeString(object.planeId!);
          final flightAddressOffset = object.flightAddress == null
              ? null
              : fbb.writeString(object.flightAddress!);
          fbb.startTable(18);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.startTimestamp);
          fbb.addInt64(2, object.durationInMs);
          fbb.addInt64(3, object.endTimestamp);
          fbb.addOffset(4, planeIdOffset);
          fbb.addFloat64(5, object.maxPressure);
          fbb.addFloat64(6, object.maxHeight);
          fbb.addFloat64(7, object.maxTemperature);
          fbb.addFloat64(8, object.farPlaneDistanceLat);
          fbb.addFloat64(9, object.farPlaneDistanceLng);
          fbb.addFloat64(10, object.startFlightLng);
          fbb.addFloat64(11, object.startFlightLat);
          fbb.addFloat64(12, object.endFlightLng);
          fbb.addFloat64(13, object.endFlightLat);
          fbb.addFloat64(14, object.maxPlaneDistanceFromStart);
          fbb.addFloat64(15, object.maxPlaneDistanceFromUser);
          fbb.addOffset(16, flightAddressOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Flight(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              durationInMs: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              startTimestamp: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6),
              endTimestamp: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              planeId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              maxPressure: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              maxHeight: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 16),
              maxTemperature: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 18),
              farPlaneDistanceLat: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 20),
              farPlaneDistanceLng: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 22),
              startFlightLng: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 24),
              startFlightLat: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 26),
              endFlightLng: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 28),
              endFlightLat: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 30),
              maxPlaneDistanceFromStart: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 32),
              maxPlaneDistanceFromUser: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 34),
              flightAddress: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 36));
          InternalToManyAccess.setRelInfo(
              object.flightData,
              store,
              RelInfo<FlightData>.toOneBacklink(
                  15, object.id, (FlightData srcObject) => srcObject.flight),
              store.box<Flight>());
          return object;
        }),
    FlightData: EntityDefinition<FlightData>(
        model: _entities[1],
        toOneRelations: (FlightData object) => [object.flight],
        toManyRelations: (FlightData object) => {},
        getId: (FlightData object) => object.id,
        setId: (FlightData object, int id) {
          object.id = id;
        },
        objectToFB: (FlightData object, fb.Builder fbb) {
          final planeIdOffset =
              object.planeId == null ? null : fbb.writeString(object.planeId!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.isConnectedToPlane);
          fbb.addInt64(2, object.flightHistoryId);
          fbb.addOffset(3, planeIdOffset);
          fbb.addInt64(4, object.timestamp);
          fbb.addFloat64(5, object.planeLat);
          fbb.addFloat64(6, object.planeLng);
          fbb.addFloat64(7, object.height);
          fbb.addFloat64(8, object.temperature);
          fbb.addFloat64(9, object.pressure);
          fbb.addFloat64(10, object.voltage);
          fbb.addFloat64(11, object.userLng);
          fbb.addFloat64(12, object.userLat);
          fbb.addBool(13, object.isInitial);
          fbb.addInt64(14, object.flight.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FlightData(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              isConnectedToPlane:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false),
              flightHistoryId: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              planeId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              timestamp: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              planeLat: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              planeLng: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 16),
              height: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 18),
              temperature: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 20),
              pressure: const fb.Float64Reader()
                  .vTableGetNullable(buffer, rootOffset, 22),
              voltage:
                  const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 24),
              userLng: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 26),
              userLat: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 28),
              isInitial: const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 30));
          object.flight.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.flight.attach(store);
          return object;
        }),
    Program: EntityDefinition<Program>(
        model: _entities[2],
        toOneRelations: (Program object) => [object.servo],
        toManyRelations: (Program object) => {},
        getId: (Program object) => object.id,
        setId: (Program object, int id) {
          object.id = id;
        },
        objectToFB: (Program object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.time);
          fbb.addInt64(2, object.rotation);
          fbb.addInt64(3, object.servo.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Program(
              time: const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              rotation:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.servo.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.servo.attach(store);
          return object;
        }),
    Servo: EntityDefinition<Servo>(
        model: _entities[3],
        toOneRelations: (Servo object) => [object.timerConfiguration],
        toManyRelations: (Servo object) => {
              RelInfo<Program>.toOneBacklink(
                      4, object.id, (Program srcObject) => srcObject.servo):
                  object.program
            },
        getId: (Servo object) => object.id,
        setId: (Servo object, int id) {
          object.id = id;
        },
        objectToFB: (Servo object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.timerConfiguration.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Servo(
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.timerConfiguration.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          object.timerConfiguration.attach(store);
          InternalToManyAccess.setRelInfo(
              object.program,
              store,
              RelInfo<Program>.toOneBacklink(
                  4, object.id, (Program srcObject) => srcObject.servo),
              store.box<Servo>());
          return object;
        }),
    TimerConfiguration: EntityDefinition<TimerConfiguration>(
        model: _entities[4],
        toOneRelations: (TimerConfiguration object) => [],
        toManyRelations: (TimerConfiguration object) => {
              RelInfo<Servo>.toOneBacklink(3, object.id,
                      (Servo srcObject) => srcObject.timerConfiguration):
                  object.servos
            },
        getId: (TimerConfiguration object) => object.id,
        setId: (TimerConfiguration object, int id) {
          object.id = id;
        },
        objectToFB: (TimerConfiguration object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.ledOn);
          fbb.addOffset(2, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TimerConfiguration(
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              ledOn:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          InternalToManyAccess.setRelInfo(
              object.servos,
              store,
              RelInfo<Servo>.toOneBacklink(3, object.id,
                  (Servo srcObject) => srcObject.timerConfiguration),
              store.box<TimerConfiguration>());
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Flight] entity fields to define ObjectBox queries.
class Flight_ {
  /// see [Flight.id]
  static final id = QueryIntegerProperty<Flight>(_entities[0].properties[0]);

  /// see [Flight.startTimestamp]
  static final startTimestamp =
      QueryIntegerProperty<Flight>(_entities[0].properties[1]);

  /// see [Flight.durationInMs]
  static final durationInMs =
      QueryIntegerProperty<Flight>(_entities[0].properties[2]);

  /// see [Flight.endTimestamp]
  static final endTimestamp =
      QueryIntegerProperty<Flight>(_entities[0].properties[3]);

  /// see [Flight.planeId]
  static final planeId =
      QueryStringProperty<Flight>(_entities[0].properties[4]);

  /// see [Flight.maxPressure]
  static final maxPressure =
      QueryDoubleProperty<Flight>(_entities[0].properties[5]);

  /// see [Flight.maxHeight]
  static final maxHeight =
      QueryDoubleProperty<Flight>(_entities[0].properties[6]);

  /// see [Flight.maxTemperature]
  static final maxTemperature =
      QueryDoubleProperty<Flight>(_entities[0].properties[7]);

  /// see [Flight.farPlaneDistanceLat]
  static final farPlaneDistanceLat =
      QueryDoubleProperty<Flight>(_entities[0].properties[8]);

  /// see [Flight.farPlaneDistanceLng]
  static final farPlaneDistanceLng =
      QueryDoubleProperty<Flight>(_entities[0].properties[9]);

  /// see [Flight.startFlightLng]
  static final startFlightLng =
      QueryDoubleProperty<Flight>(_entities[0].properties[10]);

  /// see [Flight.startFlightLat]
  static final startFlightLat =
      QueryDoubleProperty<Flight>(_entities[0].properties[11]);

  /// see [Flight.endFlightLng]
  static final endFlightLng =
      QueryDoubleProperty<Flight>(_entities[0].properties[12]);

  /// see [Flight.endFlightLat]
  static final endFlightLat =
      QueryDoubleProperty<Flight>(_entities[0].properties[13]);

  /// see [Flight.maxPlaneDistanceFromStart]
  static final maxPlaneDistanceFromStart =
      QueryDoubleProperty<Flight>(_entities[0].properties[14]);

  /// see [Flight.maxPlaneDistanceFromUser]
  static final maxPlaneDistanceFromUser =
      QueryDoubleProperty<Flight>(_entities[0].properties[15]);

  /// see [Flight.flightAddress]
  static final flightAddress =
      QueryStringProperty<Flight>(_entities[0].properties[16]);
}

/// [FlightData] entity fields to define ObjectBox queries.
class FlightData_ {
  /// see [FlightData.id]
  static final id =
      QueryIntegerProperty<FlightData>(_entities[1].properties[0]);

  /// see [FlightData.isConnectedToPlane]
  static final isConnectedToPlane =
      QueryBooleanProperty<FlightData>(_entities[1].properties[1]);

  /// see [FlightData.flightHistoryId]
  static final flightHistoryId =
      QueryIntegerProperty<FlightData>(_entities[1].properties[2]);

  /// see [FlightData.planeId]
  static final planeId =
      QueryStringProperty<FlightData>(_entities[1].properties[3]);

  /// see [FlightData.timestamp]
  static final timestamp =
      QueryIntegerProperty<FlightData>(_entities[1].properties[4]);

  /// see [FlightData.planeLat]
  static final planeLat =
      QueryDoubleProperty<FlightData>(_entities[1].properties[5]);

  /// see [FlightData.planeLng]
  static final planeLng =
      QueryDoubleProperty<FlightData>(_entities[1].properties[6]);

  /// see [FlightData.height]
  static final height =
      QueryDoubleProperty<FlightData>(_entities[1].properties[7]);

  /// see [FlightData.temperature]
  static final temperature =
      QueryDoubleProperty<FlightData>(_entities[1].properties[8]);

  /// see [FlightData.pressure]
  static final pressure =
      QueryDoubleProperty<FlightData>(_entities[1].properties[9]);

  /// see [FlightData.voltage]
  static final voltage =
      QueryDoubleProperty<FlightData>(_entities[1].properties[10]);

  /// see [FlightData.userLng]
  static final userLng =
      QueryDoubleProperty<FlightData>(_entities[1].properties[11]);

  /// see [FlightData.userLat]
  static final userLat =
      QueryDoubleProperty<FlightData>(_entities[1].properties[12]);

  /// see [FlightData.isInitial]
  static final isInitial =
      QueryBooleanProperty<FlightData>(_entities[1].properties[13]);

  /// see [FlightData.flight]
  static final flight =
      QueryRelationToOne<FlightData, Flight>(_entities[1].properties[14]);
}

/// [Program] entity fields to define ObjectBox queries.
class Program_ {
  /// see [Program.id]
  static final id = QueryIntegerProperty<Program>(_entities[2].properties[0]);

  /// see [Program.time]
  static final time = QueryIntegerProperty<Program>(_entities[2].properties[1]);

  /// see [Program.rotation]
  static final rotation =
      QueryIntegerProperty<Program>(_entities[2].properties[2]);

  /// see [Program.servo]
  static final servo =
      QueryRelationToOne<Program, Servo>(_entities[2].properties[3]);
}

/// [Servo] entity fields to define ObjectBox queries.
class Servo_ {
  /// see [Servo.id]
  static final id = QueryIntegerProperty<Servo>(_entities[3].properties[0]);

  /// see [Servo.name]
  static final name = QueryStringProperty<Servo>(_entities[3].properties[1]);

  /// see [Servo.timerConfiguration]
  static final timerConfiguration =
      QueryRelationToOne<Servo, TimerConfiguration>(_entities[3].properties[2]);
}

/// [TimerConfiguration] entity fields to define ObjectBox queries.
class TimerConfiguration_ {
  /// see [TimerConfiguration.id]
  static final id =
      QueryIntegerProperty<TimerConfiguration>(_entities[4].properties[0]);

  /// see [TimerConfiguration.ledOn]
  static final ledOn =
      QueryBooleanProperty<TimerConfiguration>(_entities[4].properties[1]);

  /// see [TimerConfiguration.name]
  static final name =
      QueryStringProperty<TimerConfiguration>(_entities[4].properties[2]);
}
